import type { Trip, TripMember, Activity, AuditEntry, Profile, Accommodation } from "./types"

export const mockUser: Profile = {
  id: "user-1",
  display_name: "You",
  avatar_url: "",
}

export const mockMembers: Profile[] = [
  mockUser,
  { id: "user-2", display_name: "Maria", avatar_url: "" },
  { id: "user-3", display_name: "Dad", avatar_url: "" },
  { id: "user-4", display_name: "Mom", avatar_url: "" },
]

export const mockTrips: Trip[] = [
  {
    id: "trip-1",
    name: "Barcelona Family Vacation",
    destination: "Barcelona, Spain",
    start_date: "2026-04-10",
    end_date: "2026-04-19",
    created_by: "user-1",
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-22T14:00:00Z",
  },
  {
    id: "trip-2",
    name: "Weekend in Porto",
    destination: "Porto, Portugal",
    start_date: "2026-05-01",
    end_date: "2026-05-03",
    created_by: "user-1",
    created_at: "2026-03-18T09:00:00Z",
    updated_at: "2026-03-18T09:00:00Z",
  },
]

export const mockTripMembers: TripMember[] = [
  { trip_id: "trip-1", user_id: "user-1", role: "owner", profile: mockMembers[0] },
  { trip_id: "trip-1", user_id: "user-2", role: "editor", profile: mockMembers[1] },
  { trip_id: "trip-1", user_id: "user-3", role: "editor", profile: mockMembers[2] },
  { trip_id: "trip-1", user_id: "user-4", role: "viewer", profile: mockMembers[3] },
]

export const mockActivities: Activity[] = [
  // Day 1 - April 10
  {
    id: "act-1",
    trip_id: "trip-1",
    date: "2026-04-10",
    start_time: "09:00",
    end_time: "11:00",
    block: "morning",
    title: "La Sagrada Familia",
    description: "Gaudi's masterpiece basilica. Book tickets online in advance!",
    category: "activity",
    location: "La Sagrada Familia, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.4036,
    longitude: 2.1744,
    cost: 26,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-1",
    votes: { up: 4, down: 0, userVote: 1 },
  },
  {
    id: "act-2",
    trip_id: "trip-1",
    date: "2026-04-10",
    start_time: "11:30",
    end_time: "13:00",
    block: "morning",
    title: "Park Güell",
    description: "Amazing views of the city. Wear comfortable shoes!",
    category: "activity",
    location: "Park Güell, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.4145,
    longitude: 2.1527,
    cost: 10,
    currency: "EUR",
    sort_order: 1,
    created_by: "user-2",
    votes: { up: 3, down: 0, userVote: 1 },
  },
  {
    id: "act-3",
    trip_id: "trip-1",
    date: "2026-04-10",
    start_time: "13:30",
    end_time: "15:00",
    block: "afternoon",
    title: "Lunch at La Boqueria Market",
    description: "Fresh seafood tapas at the famous market on La Rambla.",
    category: "food",
    location: "Mercat de la Boqueria, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3816,
    longitude: 2.1719,
    cost: 25,
    currency: "EUR",
    sort_order: 2,
    created_by: "user-1",
    votes: { up: 2, down: 1, userVote: 0 },
  },
  {
    id: "act-4",
    trip_id: "trip-1",
    date: "2026-04-10",
    start_time: "15:30",
    end_time: "17:30",
    block: "afternoon",
    title: "Gothic Quarter Walk",
    description: "Wander through the medieval streets and discover hidden plazas.",
    category: "activity",
    location: "Barri Gòtic, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3833,
    longitude: 2.1761,
    cost: 0,
    currency: "EUR",
    sort_order: 3,
    created_by: "user-3",
    votes: { up: 3, down: 0, userVote: 1 },
  },
  {
    id: "act-5",
    trip_id: "trip-1",
    date: "2026-04-10",
    start_time: "20:00",
    end_time: "22:00",
    block: "evening",
    title: "Dinner at El Born",
    description: "Tapas dinner at a cozy restaurant in El Born neighborhood.",
    category: "food",
    location: "El Born, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3851,
    longitude: 2.1834,
    cost: 35,
    currency: "EUR",
    sort_order: 4,
    created_by: "user-2",
    votes: { up: 4, down: 0, userVote: 1 },
  },
  // Day 2 - April 11
  {
    id: "act-6",
    trip_id: "trip-1",
    date: "2026-04-11",
    start_time: "09:00",
    end_time: "10:00",
    block: "morning",
    title: "Breakfast at Hotel",
    description: null,
    category: "food",
    location: "Hotel Arts Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3879,
    longitude: 2.1942,
    cost: 0,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-1",
    votes: { up: 0, down: 0, userVote: 0 },
  },
  {
    id: "act-7",
    trip_id: "trip-1",
    date: "2026-04-11",
    start_time: "10:30",
    end_time: "13:00",
    block: "morning",
    title: "Barceloneta Beach",
    description: "Morning at the beach, bring sunscreen!",
    category: "activity",
    location: "Barceloneta Beach",
    location_url: null,
    place_id: null,
    latitude: 41.3784,
    longitude: 2.1925,
    cost: 0,
    currency: "EUR",
    sort_order: 1,
    created_by: "user-4",
    votes: { up: 2, down: 1, userVote: 0 },
  },
  {
    id: "act-8",
    trip_id: "trip-1",
    date: "2026-04-11",
    start_time: "13:30",
    end_time: "15:00",
    block: "afternoon",
    title: "Seafood Paella Lunch",
    description: "Try authentic paella at a beachfront restaurant.",
    category: "food",
    location: "Barceloneta, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3795,
    longitude: 2.1890,
    cost: 20,
    currency: "EUR",
    sort_order: 2,
    created_by: "user-1",
    votes: { up: 4, down: 0, userVote: 1 },
  },
  // Day 3 - April 12
  {
    id: "act-9",
    trip_id: "trip-1",
    date: "2026-04-12",
    start_time: "10:00",
    end_time: "13:00",
    block: "morning",
    title: "Casa Batlló",
    description: "Another Gaudi masterpiece. The immersive experience is worth it.",
    category: "activity",
    location: "Casa Batlló, Passeig de Gràcia",
    location_url: null,
    place_id: null,
    latitude: 41.3916,
    longitude: 2.1650,
    cost: 35,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-2",
    votes: { up: 3, down: 1, userVote: 1 },
  },
  // Day 4 - April 13 (move to Airbnb + explore Gothic Quarter)
  {
    id: "act-10",
    trip_id: "trip-1",
    date: "2026-04-13",
    start_time: "10:00",
    end_time: "11:00",
    block: "morning",
    title: "Check out Hotel Arts",
    description: "Pack bags and check out. Store luggage if needed.",
    category: "accommodation",
    location: "Hotel Arts Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3879,
    longitude: 2.1942,
    cost: 0,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-1",
    votes: { up: 0, down: 0, userVote: 0 },
  },
  {
    id: "act-11",
    trip_id: "trip-1",
    date: "2026-04-13",
    start_time: "11:00",
    end_time: "14:00",
    block: "morning",
    title: "Montjuïc Castle & Gardens",
    description: "Take the cable car up for panoramic views.",
    category: "activity",
    location: "Montjuïc, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3634,
    longitude: 2.1659,
    cost: 12,
    currency: "EUR",
    sort_order: 1,
    created_by: "user-3",
    votes: { up: 2, down: 0, userVote: 0 },
  },
  {
    id: "act-12",
    trip_id: "trip-1",
    date: "2026-04-13",
    start_time: "15:00",
    end_time: "16:00",
    block: "afternoon",
    title: "Check in Airbnb Gothic Quarter",
    description: "Self check-in with keybox. Code will be sent 24h before.",
    category: "accommodation",
    location: "Carrer d'Avinyó, 42, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3810,
    longitude: 2.1770,
    cost: 0,
    currency: "EUR",
    sort_order: 2,
    created_by: "user-1",
    votes: { up: 0, down: 0, userVote: 0 },
  },
  {
    id: "act-13",
    trip_id: "trip-1",
    date: "2026-04-13",
    start_time: "20:00",
    end_time: "22:30",
    block: "evening",
    title: "Flamenco Show",
    description: "Traditional flamenco at Tablao Cordobes on La Rambla.",
    category: "activity",
    location: "Tablao Cordobes, La Rambla",
    location_url: null,
    place_id: null,
    latitude: 41.3805,
    longitude: 2.1735,
    cost: 45,
    currency: "EUR",
    sort_order: 3,
    created_by: "user-2",
    votes: { up: 3, down: 0, userVote: 1 },
  },
  // Day 5 - April 14 (beach & chill day)
  {
    id: "act-14",
    trip_id: "trip-1",
    date: "2026-04-14",
    start_time: "09:30",
    end_time: "10:30",
    block: "morning",
    title: "Breakfast at Federal Café",
    description: "Great brunch spot in the Gothic Quarter, near the apartment.",
    category: "food",
    location: "Federal Café, Passatge de la Pau",
    location_url: null,
    place_id: null,
    latitude: 41.3790,
    longitude: 2.1780,
    cost: 15,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-4",
    votes: { up: 2, down: 0, userVote: 1 },
  },
  {
    id: "act-15",
    trip_id: "trip-1",
    date: "2026-04-14",
    start_time: "11:00",
    end_time: "13:30",
    block: "morning",
    title: "Picasso Museum",
    description: "One of the most extensive collections of Picasso's early work.",
    category: "activity",
    location: "Museu Picasso, Carrer Montcada",
    location_url: null,
    place_id: null,
    latitude: 41.3852,
    longitude: 2.1810,
    cost: 12,
    currency: "EUR",
    sort_order: 1,
    created_by: "user-2",
    votes: { up: 4, down: 0, userVote: 1 },
  },
  {
    id: "act-16",
    trip_id: "trip-1",
    date: "2026-04-14",
    start_time: "14:00",
    end_time: "15:30",
    block: "afternoon",
    title: "Tapas at El Xampanyet",
    description: "Famous old-school tapas bar near Picasso Museum. Cash only!",
    category: "food",
    location: "El Xampanyet, Carrer Montcada",
    location_url: null,
    place_id: null,
    latitude: 41.3848,
    longitude: 2.1815,
    cost: 22,
    currency: "EUR",
    sort_order: 2,
    created_by: "user-3",
    votes: { up: 3, down: 1, userVote: 0 },
  },
  {
    id: "act-17",
    trip_id: "trip-1",
    date: "2026-04-14",
    start_time: "16:00",
    end_time: "18:00",
    block: "afternoon",
    title: "Shopping at Passeig de Gràcia",
    description: "High-end and local boutiques. Great architecture along the way.",
    category: "free",
    location: "Passeig de Gràcia, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3930,
    longitude: 2.1640,
    cost: 0,
    currency: "EUR",
    sort_order: 3,
    created_by: "user-4",
    votes: { up: 1, down: 2, userVote: -1 },
  },
  // Day 6 - April 15 (day trip)
  {
    id: "act-18",
    trip_id: "trip-1",
    date: "2026-04-15",
    start_time: "08:30",
    end_time: "09:30",
    block: "morning",
    title: "Train to Montserrat",
    description: "Take R5 from Plaça Espanya. Buy Tot Montserrat ticket for train + cable car + museum.",
    category: "transport",
    location: "Plaça Espanya Station",
    location_url: null,
    place_id: null,
    latitude: 41.3752,
    longitude: 2.1487,
    cost: 45,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-1",
    votes: { up: 4, down: 0, userVote: 1 },
  },
  {
    id: "act-19",
    trip_id: "trip-1",
    date: "2026-04-15",
    start_time: "10:00",
    end_time: "14:00",
    block: "morning",
    title: "Montserrat Monastery",
    description: "Visit the basilica, see the Black Madonna, and hike Sant Joan trail for incredible views.",
    category: "activity",
    location: "Montserrat Monastery",
    location_url: null,
    place_id: null,
    latitude: 41.5933,
    longitude: 1.8380,
    cost: 0,
    currency: "EUR",
    sort_order: 1,
    created_by: "user-1",
    votes: { up: 4, down: 0, userVote: 1 },
  },
  {
    id: "act-20",
    trip_id: "trip-1",
    date: "2026-04-15",
    start_time: "14:30",
    end_time: "15:30",
    block: "afternoon",
    title: "Lunch at Montserrat Cafeteria",
    description: "Simple but decent food with amazing mountain views.",
    category: "food",
    location: "Montserrat Monastery Cafeteria",
    location_url: null,
    place_id: null,
    latitude: 41.5930,
    longitude: 1.8375,
    cost: 18,
    currency: "EUR",
    sort_order: 2,
    created_by: "user-3",
    votes: { up: 1, down: 1, userVote: 0 },
  },
  {
    id: "act-21",
    trip_id: "trip-1",
    date: "2026-04-15",
    start_time: "20:00",
    end_time: "22:00",
    block: "evening",
    title: "Dinner at Cervecería Catalana",
    description: "Famous tapas bar on Passeig de Gràcia. Go early to avoid the queue!",
    category: "food",
    location: "Cervecería Catalana, Carrer de Mallorca",
    location_url: null,
    place_id: null,
    latitude: 41.3920,
    longitude: 2.1620,
    cost: 28,
    currency: "EUR",
    sort_order: 3,
    created_by: "user-2",
    votes: { up: 3, down: 0, userVote: 1 },
  },
  // Day 7 - April 16 (relax day)
  {
    id: "act-22",
    trip_id: "trip-1",
    date: "2026-04-16",
    start_time: "09:00",
    end_time: "10:00",
    block: "morning",
    title: "Churros at Granja Viader",
    description: "Iconic xurreria since 1870. Try the cacaolat!",
    category: "food",
    location: "Granja Viader, Carrer d'en Xuclà",
    location_url: null,
    place_id: null,
    latitude: 41.3830,
    longitude: 2.1710,
    cost: 8,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-4",
    votes: { up: 3, down: 0, userVote: 1 },
  },
  {
    id: "act-23",
    trip_id: "trip-1",
    date: "2026-04-16",
    start_time: "10:30",
    end_time: "12:30",
    block: "morning",
    title: "Hospital de Sant Pau",
    description: "UNESCO World Heritage modernist hospital. Less crowded than Sagrada Familia.",
    category: "activity",
    location: "Hospital Sant Pau, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.4117,
    longitude: 2.1745,
    cost: 15,
    currency: "EUR",
    sort_order: 1,
    created_by: "user-2",
    votes: { up: 2, down: 0, userVote: 1 },
  },
  {
    id: "act-24",
    trip_id: "trip-1",
    date: "2026-04-16",
    start_time: "13:00",
    end_time: "14:30",
    block: "afternoon",
    title: "Lunch at La Pepita",
    description: "Best burgers and creative tapas in Gràcia neighborhood.",
    category: "food",
    location: "La Pepita, Carrer de Còrsega",
    location_url: null,
    place_id: null,
    latitude: 41.4020,
    longitude: 2.1570,
    cost: 18,
    currency: "EUR",
    sort_order: 2,
    created_by: "user-3",
    votes: { up: 3, down: 0, userVote: 1 },
  },
  {
    id: "act-25",
    trip_id: "trip-1",
    date: "2026-04-16",
    start_time: "15:00",
    end_time: "17:30",
    block: "afternoon",
    title: "Explore Gràcia Neighborhood",
    description: "Bohemian quarter with cute plazas, vintage shops, and local vibe.",
    category: "free",
    location: "Vila de Gràcia, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.4035,
    longitude: 2.1565,
    cost: 0,
    currency: "EUR",
    sort_order: 3,
    created_by: "user-4",
    votes: { up: 2, down: 0, userVote: 0 },
  },
  // Day 8 - April 17 (move to Hostal Grau + Eixample)
  {
    id: "act-26",
    trip_id: "trip-1",
    date: "2026-04-17",
    start_time: "10:00",
    end_time: "11:00",
    block: "morning",
    title: "Check out Gothic Quarter Airbnb",
    description: "Leave keys in keybox. Checkout by 11:00.",
    category: "accommodation",
    location: "Carrer d'Avinyó, 42, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3810,
    longitude: 2.1770,
    cost: 0,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-1",
    votes: { up: 0, down: 0, userVote: 0 },
  },
  {
    id: "act-27",
    trip_id: "trip-1",
    date: "2026-04-17",
    start_time: "11:30",
    end_time: "13:30",
    block: "morning",
    title: "Fundació Joan Miró",
    description: "Modern art museum on Montjuïc hill with incredible Miró collection.",
    category: "activity",
    location: "Fundació Joan Miró, Montjuïc",
    location_url: null,
    place_id: null,
    latitude: 41.3686,
    longitude: 2.1598,
    cost: 14,
    currency: "EUR",
    sort_order: 1,
    created_by: "user-2",
    votes: { up: 3, down: 0, userVote: 1 },
  },
  {
    id: "act-28",
    trip_id: "trip-1",
    date: "2026-04-17",
    start_time: "14:00",
    end_time: "15:30",
    block: "afternoon",
    title: "Lunch at Tickets Bar",
    description: "Adrià brothers' tapas bar. Need reservation weeks ahead!",
    category: "food",
    location: "Tickets Bar, Avinguda del Paral·lel",
    location_url: null,
    place_id: null,
    latitude: 41.3745,
    longitude: 2.1650,
    cost: 40,
    currency: "EUR",
    sort_order: 2,
    created_by: "user-1",
    votes: { up: 4, down: 0, userVote: 1 },
  },
  {
    id: "act-29",
    trip_id: "trip-1",
    date: "2026-04-17",
    start_time: "16:00",
    end_time: "17:00",
    block: "afternoon",
    title: "Check in Hostal Grau",
    description: "Budget-friendly hotel near La Rambla for last 2 nights.",
    category: "accommodation",
    location: "Hostal Grau, Carrer de les Ramelleres",
    location_url: null,
    place_id: null,
    latitude: 41.3835,
    longitude: 2.1705,
    cost: 0,
    currency: "EUR",
    sort_order: 3,
    created_by: "user-1",
    votes: { up: 0, down: 0, userVote: 0 },
  },
  {
    id: "act-30",
    trip_id: "trip-1",
    date: "2026-04-17",
    start_time: "19:30",
    end_time: "21:30",
    block: "evening",
    title: "Sunset at Bunkers del Carmel",
    description: "Best hidden viewpoint in Barcelona. Bring snacks and drinks for sunset!",
    category: "activity",
    location: "Bunkers del Carmel, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.4187,
    longitude: 2.1569,
    cost: 0,
    currency: "EUR",
    sort_order: 4,
    created_by: "user-3",
    votes: { up: 4, down: 0, userVote: 1 },
  },
  // Day 9 - April 18 (Tibidabo + souvenir shopping)
  {
    id: "act-31",
    trip_id: "trip-1",
    date: "2026-04-18",
    start_time: "09:30",
    end_time: "10:30",
    block: "morning",
    title: "Breakfast at Satan's Coffee Corner",
    description: "Trendy specialty coffee shop in El Raval. Amazing avocado toast.",
    category: "food",
    location: "Satan's Coffee Corner, Carrer de l'Arc de Sant Ramon",
    location_url: null,
    place_id: null,
    latitude: 41.3821,
    longitude: 2.1735,
    cost: 12,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-2",
    votes: { up: 2, down: 0, userVote: 1 },
  },
  {
    id: "act-32",
    trip_id: "trip-1",
    date: "2026-04-18",
    start_time: "11:00",
    end_time: "15:00",
    block: "morning",
    title: "Tibidabo Amusement Park",
    description: "Vintage amusement park on the highest hill. Amazing 360° views of Barcelona and the sea.",
    category: "activity",
    location: "Tibidabo, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.4225,
    longitude: 2.1187,
    cost: 28,
    currency: "EUR",
    sort_order: 1,
    created_by: "user-3",
    votes: { up: 3, down: 1, userVote: 1 },
  },
  {
    id: "act-33",
    trip_id: "trip-1",
    date: "2026-04-18",
    start_time: "16:00",
    end_time: "18:00",
    block: "afternoon",
    title: "Souvenir Shopping on La Rambla",
    description: "Pick up last souvenirs. Avoid tourist traps, try side streets for better deals.",
    category: "free",
    location: "La Rambla, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3809,
    longitude: 2.1735,
    cost: 50,
    currency: "EUR",
    sort_order: 2,
    created_by: "user-4",
    votes: { up: 1, down: 1, userVote: 0 },
  },
  {
    id: "act-34",
    trip_id: "trip-1",
    date: "2026-04-18",
    start_time: "20:30",
    end_time: "22:30",
    block: "evening",
    title: "Farewell Dinner at Can Culleretes",
    description: "One of Barcelona's oldest restaurants (since 1786). Traditional Catalan cuisine.",
    category: "food",
    location: "Can Culleretes, Carrer d'en Quintana",
    location_url: null,
    place_id: null,
    latitude: 41.3814,
    longitude: 2.1738,
    cost: 30,
    currency: "EUR",
    sort_order: 3,
    created_by: "user-2",
    votes: { up: 4, down: 0, userVote: 1 },
  },
  // Day 10 - April 19 (departure day)
  {
    id: "act-35",
    trip_id: "trip-1",
    date: "2026-04-19",
    start_time: "08:00",
    end_time: "09:00",
    block: "morning",
    title: "Last Breakfast at Hotel",
    description: "Quick breakfast before heading to the airport.",
    category: "food",
    location: "Hostal Grau, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3835,
    longitude: 2.1705,
    cost: 0,
    currency: "EUR",
    sort_order: 0,
    created_by: "user-1",
    votes: { up: 0, down: 0, userVote: 0 },
  },
  {
    id: "act-36",
    trip_id: "trip-1",
    date: "2026-04-19",
    start_time: "09:30",
    end_time: "10:00",
    block: "morning",
    title: "Check out Hostal Grau",
    description: "Return key at reception. Store bags if flight is later.",
    category: "accommodation",
    location: "Hostal Grau, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3835,
    longitude: 2.1705,
    cost: 0,
    currency: "EUR",
    sort_order: 1,
    created_by: "user-1",
    votes: { up: 0, down: 0, userVote: 0 },
  },
  {
    id: "act-37",
    trip_id: "trip-1",
    date: "2026-04-19",
    start_time: "11:00",
    end_time: "12:00",
    block: "morning",
    title: "Airport Transfer",
    description: "Aerobus from Plaça Catalunya to T1. Runs every 5 min. Buy ticket at the stop.",
    category: "transport",
    location: "Plaça Catalunya, Barcelona",
    location_url: null,
    place_id: null,
    latitude: 41.3870,
    longitude: 2.1700,
    cost: 7,
    currency: "EUR",
    sort_order: 2,
    created_by: "user-1",
    votes: { up: 0, down: 0, userVote: 0 },
  },
]

export const mockAccommodations: Accommodation[] = [
  {
    id: "acc-1",
    trip_id: "trip-1",
    name: "Hotel Arts Barcelona",
    type: "hotel",
    check_in: "2026-04-10",
    check_out: "2026-04-13",
    address: "Carrer de la Marina, 19-21, 08005 Barcelona",
    latitude: 41.3879,
    longitude: 2.1942,
    booking_url: null,
    cost_per_night: 180,
    currency: "EUR",
    notes: "Sea view room, breakfast included",
  },
  {
    id: "acc-2",
    trip_id: "trip-1",
    name: "Gothic Quarter Apartment",
    type: "airbnb",
    check_in: "2026-04-13",
    check_out: "2026-04-17",
    address: "Carrer d'Avinyó, 42, 08002 Barcelona",
    latitude: 41.3810,
    longitude: 2.1770,
    booking_url: null,
    cost_per_night: 120,
    currency: "EUR",
    notes: "2-bedroom flat, self check-in with keybox",
  },
  {
    id: "acc-3",
    trip_id: "trip-1",
    name: "Hostal Grau",
    type: "hotel",
    check_in: "2026-04-17",
    check_out: "2026-04-19",
    address: "Carrer de les Ramelleres, 27, 08001 Barcelona",
    latitude: 41.3835,
    longitude: 2.1705,
    booking_url: null,
    cost_per_night: 85,
    currency: "EUR",
    notes: "Budget-friendly, near La Rambla. Great location for last days.",
  },
]

// Helper to get accommodation for a specific date
export function getAccommodationForDate(date: string, tripId: string = "trip-1"): Accommodation | null {
  return mockAccommodations.find(
    (a) => a.trip_id === tripId && date >= a.check_in && date < a.check_out
  ) || null
}

export const mockAuditLog: AuditEntry[] = [
  {
    id: "audit-1",
    trip_id: "trip-1",
    actor_name: "Claude",
    action: "create",
    entity_type: "activity",
    description: 'Generated 5 activities for April 10',
    created_at: "2026-03-22T14:00:00Z",
  },
  {
    id: "audit-2",
    trip_id: "trip-1",
    actor_name: "Maria",
    action: "create",
    entity_type: "activity",
    description: 'Added "Park Güell" to April 10 morning',
    created_at: "2026-03-22T14:30:00Z",
  },
  {
    id: "audit-3",
    trip_id: "trip-1",
    actor_name: "Dad",
    action: "vote",
    entity_type: "activity",
    description: 'Voted 👍 on "La Sagrada Familia"',
    created_at: "2026-03-22T15:00:00Z",
  },
  {
    id: "audit-4",
    trip_id: "trip-1",
    actor_name: "You",
    action: "update",
    entity_type: "activity",
    description: 'Moved "Dinner at El Born" to evening',
    created_at: "2026-03-22T15:15:00Z",
  },
  {
    id: "audit-5",
    trip_id: "trip-1",
    actor_name: "Mom",
    action: "create",
    entity_type: "activity",
    description: 'Added "Barceloneta Beach" to April 11',
    created_at: "2026-03-22T16:00:00Z",
  },
]

// Helper to get activities for a specific date
export function getActivitiesByDate(date: string): Activity[] {
  return mockActivities
    .filter((a) => a.date === date)
    .sort((a, b) => a.sort_order - b.sort_order)
}

// Helper to get all dates for a trip
export function getTripDates(trip: Trip): string[] {
  const dates: string[] = []
  const start = new Date(trip.start_date)
  const end = new Date(trip.end_date)
  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    dates.push(d.toISOString().split("T")[0])
  }
  return dates
}
